/*
 * Copyright (c) 2023 EPAM Systems
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_RZA2_DMA_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_RZA2_DMA_H_

#define DMA_MEM_2_MEM            0
#define DMA_RS_OSTM0TINT         1
#define DMA_RS_OSTM1TINT         2
#define DMA_RS_OSTM2TINT         3
#define DMA_RS_TGIA_0            4
#define DMA_RS_TGIB_0            5
#define DMA_RS_TGIC_0            6
#define DMA_RS_TGID_0            7
#define DMA_RS_TGIA_1            8
#define DMA_RS_TGIB_1            9
#define DMA_RS_TGIA_2            10
#define DMA_RS_TGIB_2            11
#define DMA_RS_TGIA_3            12
#define DMA_RS_TGIB_3            13
#define DMA_RS_TGIC_3            14
#define DMA_RS_TGID_3            15
#define DMA_RS_TGIA_4            16
#define DMA_RS_TGIB_4            17
#define DMA_RS_TGIC_4            18
#define DMA_RS_TGID_4            19
#define DMA_RS_TCIV_4            20
#define DMA_RS_TGIU_5            21
#define DMA_RS_TGIV_5            22
#define DMA_RS_TGIW_5            23
#define DMA_RS_TGIA_6            24
#define DMA_RS_TGIB_6            25
#define DMA_RS_TGIC_6            26
#define DMA_RS_TGID_6            27
#define DMA_RS_TGIA_7            28
#define DMA_RS_TGIB_7            29
#define DMA_RS_TGIC_7            30
#define DMA_RS_TGID_7            31
#define DMA_RS_TCIV_7            32
#define DMA_RS_TGIA_8            33
#define DMA_RS_TGIB_8            34
#define DMA_RS_TGIC_8            35
#define DMA_RS_TGID_8            36
#define DMA_RS_GTCIA_0           37
#define DMA_RS_GTCIB_0           38
#define DMA_RS_GTCIC_0           39
#define DMA_RS_GTCID_0           40
#define DMA_RS_GDTE_0            41
#define DMA_RS_GTCIH_0           42
#define DMA_RS_GTCIL_0           43
#define DMA_RS_GTCIE_0           44
#define DMA_RS_GTCIF_0           45
#define DMA_RS_GTCIADA_0         46
#define DMA_RS_GTCIADB_0         47
#define DMA_RS_GTCIV_0           48
#define DMA_RS_GTCIU_0           49
#define DMA_RS_GTCIA_1           50
#define DMA_RS_GTCIB_1           51
#define DMA_RS_GTCIC_1           52
#define DMA_RS_GTCID_1           53
#define DMA_RS_GDTE_1            54
#define DMA_RS_GTCIH_1           55
#define DMA_RS_GTCIL_1           56
#define DMA_RS_GTCIE_1           57
#define DMA_RS_GTCIF_1           58
#define DMA_RS_GTCIADA_1         59
#define DMA_RS_GTCIADB_1         60
#define DMA_RS_GTCIV_1           61
#define DMA_RS_GTCIU_1           62
#define DMA_RS_GTCIA_2           63
#define DMA_RS_GTCIB_2           64
#define DMA_RS_GTCIC_2           65
#define DMA_RS_GTCID_2           66
#define DMA_RS_GDTE_2            67
#define DMA_RS_GTCIH_2           68
#define DMA_RS_GTCIL_2           69
#define DMA_RS_GTCIE_2           70
#define DMA_RS_GTCIF_2           71
#define DMA_RS_GTCIADA_2         72
#define DMA_RS_GTCIADB_2         73
#define DMA_RS_GTCIV_2           74
#define DMA_RS_GTCIU_2           75
#define DMA_RS_GTCIA_3           76
#define DMA_RS_GTCIB_3           77
#define DMA_RS_GTCIC_3           78
#define DMA_RS_GTCID_3           79
#define DMA_RS_GDTE_3            80
#define DMA_RS_GTCIH_3           81
#define DMA_RS_GTCIL_3           82
#define DMA_RS_GTCIE_3           83
#define DMA_RS_GTCIF_3           84
#define DMA_RS_GTCIADA_3         85
#define DMA_RS_GTCIADB_3         86
#define DMA_RS_GTCIV_3           87
#define DMA_RS_GTCIU_3           88
#define DMA_RS_GTCIA_4           89
#define DMA_RS_GTCIB_4           90
#define DMA_RS_GTCIC_4           91
#define DMA_RS_GTCID_4           92
#define DMA_RS_GDTE_4            93
#define DMA_RS_GTCIH_4           94
#define DMA_RS_GTCIL_4           95
#define DMA_RS_GTCIE_4           96
#define DMA_RS_GTCIF_4           97
#define DMA_RS_GTCIADA_4         98
#define DMA_RS_GTCIADB_4         99
#define DMA_RS_GTCIV_4           100
#define DMA_RS_GTCIU_4           101
#define DMA_RS_GTCIA_5           102
#define DMA_RS_GTCIB_5           103
#define DMA_RS_GTCIC_5           104
#define DMA_RS_GTCID_5           105
#define DMA_RS_GDTE_5            106
#define DMA_RS_GTCIH_5           107
#define DMA_RS_GTCIL_5           108
#define DMA_RS_GTCIE_5           109
#define DMA_RS_GTCIF_5           110
#define DMA_RS_GTCIADA_5         111
#define DMA_RS_GTCIADB_5         112
#define DMA_RS_GTCIV_5           113
#define DMA_RS_GTCIU_5           114
#define DMA_RS_GTCIA_6           115
#define DMA_RS_GTCIB_6           116
#define DMA_RS_GTCIC_6           117
#define DMA_RS_GTCID_6           118
#define DMA_RS_GDTE_6            119
#define DMA_RS_GTCIH_6           120
#define DMA_RS_GTCIL_6           121
#define DMA_RS_GTCIE_6           122
#define DMA_RS_GTCIF_6           123
#define DMA_RS_GTCIADA_6         124
#define DMA_RS_GTCIADB_6         125
#define DMA_RS_GTCIV_6           126
#define DMA_RS_GTCIU_6           127
#define DMA_RS_GTCIA_7           128
#define DMA_RS_GTCIB_7           129
#define DMA_RS_GTCIC_7           130
#define DMA_RS_GTCID_7           131
#define DMA_RS_GDTE_7            132
#define DMA_RS_GTCIH_7           133
#define DMA_RS_GTCIL_7           134
#define DMA_RS_GTCIE_7           135
#define DMA_RS_GTCIF_7           136
#define DMA_RS_GTCIADA_7         137
#define DMA_RS_GTCIADB_7         138
#define DMA_RS_GTCIV_7           139
#define DMA_RS_GTCIU_7           140
#define DMA_RS_S12ADI_0          141
#define DMA_RS_S12GBADI_0        142
#define DMA_RS_S12GCADI_0        143
#define DMA_RS_INT_SSIF_DMA_RX_0 144
#define DMA_RS_INT_SSIF_DMA_TX_0 145
#define DMA_RS_INT_SSIF_DMA_RX_1 146
#define DMA_RS_INT_SSIF_DMA_TX_1 147
#define DMA_RS_INT_SSIF_DMA_RX_2 148
#define DMA_RS_INT_SSIF_DMA_TX_2 149
#define DMA_RS_INT_SSIF_DMA_RX_3 150
#define DMA_RS_INT_SSIF_DMA_TX_3 151
#define DMA_RS_SPDIFTXI          152
#define DMA_RS_SPDIFRXI          153
#define DMA_RS_INTRIIC_RI0       154
#define DMA_RS_INTRIIC_TI0       155
#define DMA_RS_INTRIIC_RI1       156
#define DMA_RS_INTRIIC_TI1       157
#define DMA_RS_INTRIIC_RI2       158
#define DMA_RS_INTRIIC_TI2       159
#define DMA_RS_INTRIIC_RI3       160
#define DMA_RS_INTRIIC_TI3       161
#define DMA_RS_RXI0              162
#define DMA_RS_TXI0              163
#define DMA_RS_RXI1              164
#define DMA_RS_TXI1              165
#define DMA_RS_RXI2              166
#define DMA_RS_TXI2              167
#define DMA_RS_RXI3              168
#define DMA_RS_TXI3              169
#define DMA_RS_RXI4              170
#define DMA_RS_TXI4              171
#define DMA_RS_RXF_DMA0          172
#define DMA_RS_RXF_DMA1          173
#define DMA_RS_RXF_DMA2          174
#define DMA_RS_RXF_DMA3          175
#define DMA_RS_RXF_DMA4          176
#define DMA_RS_RXF_DMA5          177
#define DMA_RS_RXF_DMA6          178
#define DMA_RS_RXF_DMA7          179
#define DMA_RS_COM_DMA0          180
#define DMA_RS_COM_DMA1          181
#define DMA_RS_SPRI0             182
#define DMA_RS_SPTI0             183
#define DMA_RS_SPRI1             184
#define DMA_RS_SPTI1             185
#define DMA_RS_SPRI2             186
#define DMA_RS_SPTI2             187
#define DMA_RS_SCI_RXI0          188
#define DMA_RS_SCI_TXI0          189
#define DMA_RS_SCI_RXI1          190
#define DMA_RS_SCI_TXI1          191
#define DMA_RS_IPLS              192
#define DMA_RS_TILE_0_PAFI       193
#define DMA_RS_TILE_0_PAEI       194
#define DMA_RS_TILE_1_PAFI       195
#define DMA_RS_TILE_1_PAEI       196
#define DMA_RS_TILE_2_PAFI       197
#define DMA_RS_TILE_2_PAEI       198
#define DMA_RS_TILE_3_PAFI       199
#define DMA_RS_TILE_3_PAEI       200
#define DMA_RS_TILE_4_PAFI       201
#define DMA_RS_TILE_4_PAEI       202
#define DMA_RS_TILE_5_PAFI       203
#define DMA_RS_TILE_5_PAEI       204
#define DREQ0                    205
#define LAST_RESOURCE_MARKER     206

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_RZA2_DMA_H_ */
