/*
 * Copyright (c) 2023 Epam Systems
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef __SPI_RZA2_H_
#define __SPI_RZA2_H_

#define CMNCR_OFF      (0x00)
#define SSLDR_OFF      (0x04)
#define DRCR_OFF       (0x0C)
#define DRCMR_OFF      (0x10)
#define DREAR_OFF      (0x14)
#define DROPR_OFF      (0x18)
#define DRENR_OFF      (0x1C)
#define SMCR_OFF       (0x20)
#define SMCMR_OFF      (0x24)
#define SMADR_OFF      (0x28)
#define SMOPR_OFF      (0x2C)
#define SMENR_OFF      (0x30)
#define SMRDR0_OFF     (0x38)
#define SMRDR1_OFF     (0x3C)
#define SMWDR0_OFF     (0x40)
#define SMWDR1_OFF     (0x44)
#define CMNSR_OFF      (0x48)
#define DRDMCR_OFF     (0x58)
#define DRDRENR_OFF    (0x5C)
#define SMDMCR_OFF     (0x60)
#define SMDRENR_OFF    (0x64)
#define PHYCNT_OFF     (0x7C)
#define PHYOFFSET1_OFF (0x80)
#define PHYOFFSET2_OFF (0x84)
#define PHYINT_OFF     (0x88)
#define PHYADJ1_OFF    (0x70)
#define PHYADJ2_OFF    (0x74)

#define SPI_CMNCR_BSZ               (0x00000003u)
#define SPI_CMNCR_BSZ_SHIFT         (0u)
#define SPI_CMNCR_IO0FV             (0x00000300u)
#define SPI_CMNCR_IO0FV_SHIFT       (8u)
#define SPI_CMNCR_IO2FV             (0x00003000u)
#define SPI_CMNCR_IO2FV_SHIFT       (12u)
#define SPI_CMNCR_IO3FV             (0x0000C000u)
#define SPI_CMNCR_IO3FV_SHIFT       (14u)
#define SPI_CMNCR_MOIIO0            (0x00030000u)
#define SPI_CMNCR_MOIIO0_SHIFT      (16u)
#define SPI_CMNCR_MOIIO1            (0x000C0000u)
#define SPI_CMNCR_MOIIO1_SHIFT      (18u)
#define SPI_CMNCR_MOIIO2            (0x00300000u)
#define SPI_CMNCR_MOIIO2_SHIFT      (20u)
#define SPI_CMNCR_MOIIO3            (0x00C00000u)
#define SPI_CMNCR_MOIIO3_SHIFT      (22u)
#define SPI_CMNCR_RESERV_SHIFT      (24u)
#define SPI_CMNCR_MD                (0x80000000u)
#define SPI_CMNCR_MD_SHIFT          (31u)
#define SPI_SSLDR_SCKDL             (0x00000007u)
#define SPI_SSLDR_SCKDL_SHIFT       (0u)
#define SPI_SSLDR_SLNDL             (0x00000700u)
#define SPI_SSLDR_SLNDL_SHIFT       (8u)
#define SPI_SSLDR_SPNDL             (0x00070000u)
#define SPI_SSLDR_SPNDL_SHIFT       (16u)
#define SPI_DRCR_SSLE               (0x00000001u)
#define SPI_DRCR_SSLE_SHIFT         (0u)
#define SPI_DRCR_RBE                (0x00000100u)
#define SPI_DRCR_RBE_SHIFT          (8u)
#define SPI_DRCR_RCF                (0x00000200u)
#define SPI_DRCR_RCF_SHIFT          (9u)
#define SPI_DRCR_RBURST             (0x001F0000u)
#define SPI_DRCR_RBURST_SHIFT       (16u)
#define SPI_DRCR_SSLN               (0x01000000u)
#define SPI_DRCR_SSLN_SHIFT         (24u)
#define SPI_DRCMR_OCMD              (0x000000FFu)
#define SPI_DRCMR_OCMD_SHIFT        (0u)
#define SPI_DRCMR_CMD               (0x00FF0000u)
#define SPI_DRCMR_CMD_SHIFT         (16u)
#define SPI_DREAR_EAC               (0x00000007u)
#define SPI_DREAR_EAC_SHIFT         (0u)
#define SPI_DREAR_EAV               (0x00FF0000u)
#define SPI_DREAR_EAV_SHIFT         (16u)
#define SPI_DROPR_OPD0              (0x000000FFu)
#define SPI_DROPR_OPD0_SHIFT        (0u)
#define SPI_DROPR_OPD1              (0x0000FF00u)
#define SPI_DROPR_OPD1_SHIFT        (8u)
#define SPI_DROPR_OPD2              (0x00FF0000u)
#define SPI_DROPR_OPD2_SHIFT        (16u)
#define SPI_DROPR_OPD3              (0xFF000000u)
#define SPI_DROPR_OPD3_SHIFT        (24u)
#define SPI_DRENR_OPDE              (0x000000F0u)
#define SPI_DRENR_OPDE_SHIFT        (4u)
#define SPI_DRENR_ADE               (0x00000F00u)
#define SPI_DRENR_ADE_SHIFT         (8u)
#define SPI_DRENR_OCDE              (0x00001000u)
#define SPI_DRENR_OCDE_SHIFT        (12u)
#define SPI_DRENR_CDE               (0x00004000u)
#define SPI_DRENR_CDE_SHIFT         (14u)
#define SPI_DRENR_DME               (0x00008000u)
#define SPI_DRENR_DME_SHIFT         (15u)
#define SPI_DRENR_DRDB              (0x00030000u)
#define SPI_DRENR_DRDB_SHIFT        (16u)
#define SPI_DRENR_OPDB              (0x00300000u)
#define SPI_DRENR_OPDB_SHIFT        (20u)
#define SPI_DRENR_ADB               (0x03000000u)
#define SPI_DRENR_ADB_SHIFT         (24u)
#define SPI_DRENR_OCDB              (0x30000000u)
#define SPI_DRENR_OCDB_SHIFT        (28u)
#define SPI_DRENR_CDB               (0xC0000000u)
#define SPI_DRENR_CDB_SHIFT         (30u)
#define SPI_SMCR_SPIE               (0x00000001u)
#define SPI_SMCR_SPIE_SHIFT         (0u)
#define SPI_SMCR_SPIWE              (0x00000002u)
#define SPI_SMCR_SPIWE_SHIFT        (1u)
#define SPI_SMCR_SPIRE              (0x00000004u)
#define SPI_SMCR_SPIRE_SHIFT        (2u)
#define SPI_SMCR_SSLKP              (0x00000100u)
#define SPI_SMCR_SSLKP_SHIFT        (8u)
#define SPI_SMCMR_OCMD              (0x000000FFu)
#define SPI_SMCMR_OCMD_SHIFT        (0u)
#define SPI_SMCMR_CMD               (0x00FF0000u)
#define SPI_SMCMR_CMD_SHIFT         (16u)
#define SPI_SMADR_ADR               (0xFFFFFFFFu)
#define SPI_SMADR_ADR_SHIFT         (0u)
#define SPI_SMOPR_OPD0              (0x000000FFu)
#define SPI_SMOPR_OPD0_SHIFT        (0u)
#define SPI_SMOPR_OPD1              (0x0000FF00u)
#define SPI_SMOPR_OPD1_SHIFT        (8u)
#define SPI_SMOPR_OPD2              (0x00FF0000u)
#define SPI_SMOPR_OPD2_SHIFT        (16u)
#define SPI_SMOPR_OPD3              (0xFF000000u)
#define SPI_SMOPR_OPD3_SHIFT        (24u)
#define SPI_SMENR_SPIDE             (0x0000000Fu)
#define SPI_SMENR_SPIDE_SHIFT       (0u)
#define SPI_SMENR_OPDE              (0x000000F0u)
#define SPI_SMENR_OPDE_SHIFT        (4u)
#define SPI_SMENR_ADE               (0x00000F00u)
#define SPI_SMENR_ADE_SHIFT         (8u)
#define SPI_SMENR_OCDE              (0x00001000u)
#define SPI_SMENR_OCDE_SHIFT        (12u)
#define SPI_SMENR_CDE               (0x00004000u)
#define SPI_SMENR_CDE_SHIFT         (14u)
#define SPI_SMENR_DME               (0x00008000u)
#define SPI_SMENR_DME_SHIFT         (15u)
#define SPI_SMENR_SPIDB             (0x00030000u)
#define SPI_SMENR_SPIDB_SHIFT       (16u)
#define SPI_SMENR_OPDB              (0x00300000u)
#define SPI_SMENR_OPDB_SHIFT        (20u)
#define SPI_SMENR_ADB               (0x03000000u)
#define SPI_SMENR_ADB_SHIFT         (24u)
#define SPI_SMENR_OCDB              (0x30000000u)
#define SPI_SMENR_OCDB_SHIFT        (28u)
#define SPI_SMENR_CDB               (0xC0000000u)
#define SPI_SMENR_CDB_SHIFT         (30u)
#define SPI_SMRDR0_RDATA0           (0xFFFFFFFFu)
#define SPI_SMRDR0_RDATA0_SHIFT     (0u)
#define SPI_SMRDR1_RDATA1           (0xFFFFFFFFu)
#define SPI_SMRDR1_RDATA1_SHIFT     (0u)
#define SPI_SMWDR0_WDATA0           (0xFFFFFFFFu)
#define SPI_SMWDR0_WDATA0_SHIFT     (0u)
#define SPI_SMWDR1_WDATA1           (0xFFFFFFFFu)
#define SPI_SMWDR1_WDATA1_SHIFT     (0u)
#define SPI_CMNSR_TEND              (0x00000001u)
#define SPI_CMNSR_TEND_SHIFT        (0u)
#define SPI_CMNSR_SSLF              (0x00000002u)
#define SPI_CMNSR_SSLF_SHIFT        (1u)
#define SPI_DRDMCR_DMCYC            (0x0000001Fu)
#define SPI_DRDMCR_DMCYC_SHIFT      (0u)
#define SPI_DRDRENR_DRDRE           (0x00000001u)
#define SPI_DRDRENR_DRDRE_SHIFT     (0u)
#define SPI_DRDRENR_OPDRE           (0x00000010u)
#define SPI_DRDRENR_OPDRE_SHIFT     (4u)
#define SPI_DRDRENR_ADDRE           (0x00000100u)
#define SPI_DRDRENR_ADDRE_SHIFT     (8u)
#define SPI_DRDRENR_HYPE            (0x00007000u)
#define SPI_DRDRENR_HYPE_SHIFT      (12u)
#define SPI_SMDMCR_DMCYC            (0x0000001Fu)
#define SPI_SMDMCR_DMCYC_SHIFT      (0u)
#define SPI_SMDRENR_SPIDRE          (0x00000001u)
#define SPI_SMDRENR_SPIDRE_SHIFT    (0u)
#define SPI_SMDRENR_OPDRE           (0x00000010u)
#define SPI_SMDRENR_OPDRE_SHIFT     (4u)
#define SPI_SMDRENR_ADDRE           (0x00000100u)
#define SPI_SMDRENR_ADDRE_SHIFT     (8u)
#define SPI_SMDRENR_HYPE            (0x00007000u)
#define SPI_SMDRENR_HYPE_SHIFT      (12u)
#define SPI_PHYADJ1_ADJ1            (0xFFFFFFFFu)
#define SPI_PHYADJ1_ADJ1_SHIFT      (0u)
#define SPI_PHYADJ2_ADJ2            (0xFFFFFFFFu)
#define SPI_PHYADJ2_ADJ2_SHIFT      (0u)
#define SPI_PHYCNT_PHYMEM           (0x00000003u)
#define SPI_PHYCNT_PHYMEM_SHIFT     (0u)
#define SPI_PHYCNT_WBUF             (0x00000004u)
#define SPI_PHYCNT_WBUF_SHIFT       (2u)
#define SPI_PHYCNT_WBUF2            (0x00000010u)
#define SPI_PHYCNT_WBUF2_SHIFT      (4u)
#define SPI_PHYCNT_CKSEL            (0x00030000u)
#define SPI_PHYCNT_CKSEL_SHIFT      (16u)
#define SPI_PHYCNT_HS               (0x00040000u)
#define SPI_PHYCNT_HS_SHIFT         (18u)
#define SPI_PHYCNT_OCT              (0x00100000u)
#define SPI_PHYCNT_OCT_SHIFT        (20u)
#define SPI_PHYCNT_EXDS             (0x00200000u)
#define SPI_PHYCNT_EXDS_SHIFT       (21u)
#define SPI_PHYCNT_OCTA             (0x00C00000u)
#define SPI_PHYCNT_OCTA_SHIFT       (22u)
#define SPI_PHYCNT_ALT_ALIGN        (0x40000000u)
#define SPI_PHYCNT_ALT_ALIGN_SHIFT  (30u)
#define SPI_PHYCNT_CAL              (0x80000000u)
#define SPI_PHYCNT_CAL_SHIFT        (31u)
#define SPI_PHYOFFSET1_DDRTMG       (0x30000000u)
#define SPI_PHYOFFSET1_DDRTMG_SHIFT (28u)
#define SPI_PHYOFFSET2_OCTTMG       (0x00000700u)
#define SPI_PHYOFFSET2_OCTTMG_SHIFT (8u)
#define SPI_PHYINT_INT              (0x00000001u)
#define SPI_PHYINT_INT_SHIFT        (0u)
#define SPI_PHYINT_WPVAL            (0x00000002u)
#define SPI_PHYINT_WPVAL_SHIFT      (1u)
#define SPI_PHYINT_RSTVAL           (0x00000004u)
#define SPI_PHYINT_RSTVAL_SHIFT     (2u)
#define SPI_PHYINT_INTEN            (0x01000000u)
#define SPI_PHYINT_INTEN_SHIFT      (24u)
#define SPI_PHYINT_WPEN             (0x02000000u)
#define SPI_PHYINT_WPEN_SHIFT       (25u)
#define SPI_PHYINT_RSTEN            (0x04000000u)
#define SPI_PHYINT_RSTEN_SHIFT      (26u)

/* Values definitions */
#define SPI_COUNT (1u)

#define SPI_CMNCR_MD_EXTRD (0u)
#define SPI_CMNCR_MD_SPI   (1u)

#define SPI_OUTPUT_LOW  (0u)
#define SPI_OUTPUT_HIGH (1u)
#define SPI_OUTPUT_LAST (2u)
#define SPI_OUTPUT_HiZ  (3u)

#define SPI_CMNCR_CPHAT_EVEN (0u)
#define SPI_CMNCR_CPHAT_ODD  (1u)

#define SPI_CMNCR_CPHAR_ODD  (0u)
#define SPI_CMNCR_CPHAR_EVEN (1u)

#define SPI_CMNCR_SSLP_LOW  (0u)
#define SPI_CMNCR_SSLP_HIGH (1u)

#define SPI_CMNCR_CPOL_LOW  (0u)
#define SPI_CMNCR_CPOL_HIGH (1u)

#define SPI_CMNCR_BSZ_SINGLE (0u)
#define SPI_CMNCR_BSZ_DUAL   (1u)

#define SPI_DELAY_1SPBCLK (0u)
#define SPI_DELAY_2SPBCLK (1u)
#define SPI_DELAY_3SPBCLK (2u)
#define SPI_DELAY_4SPBCLK (3u)
#define SPI_DELAY_5SPBCLK (4u)
#define SPI_DELAY_6SPBCLK (5u)
#define SPI_DELAY_7SPBCLK (6u)
#define SPI_DELAY_8SPBCLK (7u)

#define SPI_BURST_1  (0x00u)
#define SPI_BURST_2  (0x01u)
#define SPI_BURST_3  (0x02u)
#define SPI_BURST_4  (0x03u)
#define SPI_BURST_5  (0x04u)
#define SPI_BURST_6  (0x05u)
#define SPI_BURST_7  (0x06u)
#define SPI_BURST_8  (0x07u)
#define SPI_BURST_9  (0x08u)
#define SPI_BURST_10 (0x09u)
#define SPI_BURST_11 (0x0au)
#define SPI_BURST_12 (0x0bu)
#define SPI_BURST_13 (0x0cu)
#define SPI_BURST_14 (0x0du)
#define SPI_BURST_15 (0x0eu)
#define SPI_BURST_16 (0x0fu)

#define SPI_BURST_DISABLE (0u)
#define SPI_BURST_ENABLE  (1u)

#define SPI_DRCR_RCF_EXE (1u)

#define SPI_SSL_NEGATE (0u)
#define SPI_TRANS_END  (1u)

#define SPI_1BIT (0u)
#define SPI_2BIT (1u)
#define SPI_4BIT (2u)

#define SPI_OUTPUT_DISABLE  (0u)
#define SPI_OUTPUT_ENABLE   (1u)
#define SPI_OUTPUT_ADDR_24  (0x07u)
#define SPI_OUTPUT_ADDR_32  (0x0fu)
#define SPI_OUTPUT_OPD_3    (0x08u)
#define SPI_OUTPUT_OPD_32   (0x0cu)
#define SPI_OUTPUT_OPD_321  (0x0eu)
#define SPI_OUTPUT_OPD_3210 (0x0fu)

#define SPI_OUTPUT_SPID_8  (0x08u)
#define SPI_OUTPUT_SPID_16 (0x0cu)
#define SPI_OUTPUT_SPID_32 (0x0fu)

#define SPI_SPISSL_NEGATE (0u)
#define SPI_SPISSL_KEEP   (1u)

#define SPI_SPIDATA_DISABLE (0u)
#define SPI_SPIDATA_ENABLE  (1u)

#define SPI_SPI_DISABLE (0u)
#define SPI_SPI_ENABLE  (1u)
/* TODO change comments*/

/* Use for setting of the DME bit of "data read enable register"(DRENR) */
#define SPI_DUMMY_CYC_DISABLE (0u)
#define SPI_DUMMY_CYC_ENABLE  (1u)

/* Use for setting of the DMCYC [2:0] bit of "data read dummy cycle register"(DRDMCR) */
#define SPI_DUMMY_1CYC (0u)
#define SPI_DUMMY_2CYC (1u)
#define SPI_DUMMY_3CYC (2u)
#define SPI_DUMMY_4CYC (3u)
#define SPI_DUMMY_5CYC (4u)
#define SPI_DUMMY_6CYC (5u)
#define SPI_DUMMY_7CYC (6u)
#define SPI_DUMMY_8CYC (7u)

/* Use for setting of "data read DDR enable register"(DRDRENR) */
#define SPI_SDR_TRANS (0u)
#define SPI_DDR_TRANS (1u)

/* Use for setting the CKDLY register */
#define SPI_CKDLY_DEFAULT (0x0000A504uL) /* Initial value */
#define SPI_CKDLY_TUNING                                                                           \
	(0x0000A50AuL) /* Shorten the data input setup time and extend the data hold time */

/* Use for setting the SPODLY register */
#define SPI_SPODLY_DEFAULT (0xA5000000uL) /* Initial value */
#define SPI_SPODLY_TUNING                                                                          \
	(0xA5001111uL) /* Delay the data output delay/hold/buffer-on/buffer-off time */

/* Use for setting of the CAL bit of "Phy control register"(PHYCNT) */
#define SPI_CAL_DISABLE (0u)
#define SPI_CAL_ENABLE  (1u)

/* Use for setting of the OCTA[1:0] bit of "Phy control register"(PHYCNT) */
#define SPI_OCTA_HYPER      (0u)
#define SPI_OCTA_ALTER_ALIG (1u)
#define SPI_OCTA_ORDER_ALIG (2u)

/* Use for setting of the EXDS bit of "Phy control register"(PHYCNT) */
#define SPISBSC_PHYMEM_DATA_STROBE_DISABLE (0u)
#define SPISBSC_PHYMEM_DATA_STROBE_ENABLE  (1u)

/* Use for setting of the OCT bit of "Phy control register"(PHYCNT) */
#define SPI_PHYMEM_OCT_DDR_PROTOCOL_DISABLE (0u)
#define SPI_PHYMEM_OCT_DDR_PROTOCOL_ENABLE  (1u)

/* Use for setting of the HS bit of "Phy control register"(PHYCNT) */
#define SPI_PHYMEM_HIGH_SPEED_DISABLE (0u)
#define SPI_PHYMEM_HIGH_SPEED_ENABLE  (1u)

/* Use for setting of the WBUT and WBUF2 bits  of "Phy control register"(PHYCNT) */
#define SPI_PHYMEM_WRITE_BUFFER_DISABLE (0u)
#define SPI_PHYMEM_WRITE_BUFFER_ENABLE  (1u)

/* Use for setting of the PHYMEM[1:0]bit of "Phy control register"(PHYCNT) */
#define SPI_PHYMEM_SDR   (0u)
#define SPI_PHYMEM_DDR   (1u)
#define SPI_PHYMEM_HYPER (3u)

#endif /* __SPI_RZA2_H_ */
